# GAME OPTIONS
SCREENWIDTH = 1280
SCREENHEIGHT = 720
FPS = 60
TILESIZE = 32
GRAVITY = 0.1
TERMINALVELOCITY = 2

#COLORS
TEXT_COLOR = "#FFFFFF"
TEXT_COLOR2 = "#5e5e5d"
BUTTON_BACKGROUND_COLOR = "#c97442"
BUTTON_TEXT_COLOR = "#000000"

#PLAYER OPTIONS
PLAYERSPEED = 5
PLAYERJUMPPOWER = 7

#MOB OPTIONS
ZOMBIESPEED = 4
ZOMBIEJUMPPOWER = 9

# WORLD OPTIONS
COALSPAWNCHANCE = 0.15
IRONSPAWNCHANCE = 0.10
GOLDSPAWNCHANCE = 0.08

# UI
FIXED_BUTTON_WIDTH = 300
PADDING_X = 20  # Horizontal padding (left and right)
PADDING_Y = 20  # Vertical padding (top and bottom)