# GAME OPTIONS
SCREENWIDTH = 1280
SCREENHEIGHT = 720
FPS = 60
TILESIZE = 32
GRAVITY = 0.1
TERMINALVELOCITY = 2

#PLAYER OPTIONS
PLAYERSPEED = 5
PLAYERJUMPPOWER = 10

#MOB OPTIONS
ZOMBIESPEED = 4
ZOMBIEJUMPPOWER = 9

# WORLD OPTIONS
COALSPAWNCHANCE = 0.15
IRONSPAWNCHANCE = 0.10
GOLDSPAWNCHANCE = 0.08